qa_resolve_script_dir <- function() {
  script_file <- tryCatch(
    normalizePath(sys.frame(1)$ofile, winslash = "/", mustWork = FALSE),
    error = function(e) NA_character_
  )
  if (!is.na(script_file) && nzchar(script_file) && file.exists(script_file)) {
    return(dirname(script_file))
  }

  wd <- normalizePath(getwd(), winslash = "/", mustWork = FALSE)
  candidates <- unique(c(
    wd,
    file.path(wd, "QualityAssurance"),
    dirname(wd),
    file.path(dirname(wd), "QualityAssurance")
  ))
  valid <- candidates[file.exists(file.path(candidates, "framework", "test_helpers.R"))]
  if (!length(valid)) {
    stop(
      paste0(
        "Cannot locate the QualityAssurance folder from working directory: ", wd,
        ". Run the script from the project root or from inside QualityAssurance."
      ),
      call. = FALSE
    )
  }
  valid[[1]]
}

script_dir <- qa_resolve_script_dir()
source(file.path(script_dir, "framework", "test_helpers.R"))
source(file.path(script_dir, "framework", "test_framework.R"))
required_test_api <- c("qa_test", "qa_register_test", "qa_discover_tests", "qa_run_registered")
missing_test_api <- required_test_api[!vapply(required_test_api, exists, logical(1), mode = "function", inherits = TRUE)]
if (length(missing_test_api)) stop("Test framework failed to load: ", paste(missing_test_api, collapse = ", "), call. = FALSE)
QA_ROOT <- qa_find_root(dirname(script_dir))
assign("QA_ROOT", QA_ROOT, envir = globalenv())
assign("QA_PROJECT_ROOT", QA_ROOT, envir = globalenv()) # compatibility alias for older QA tests

# Remove reports generated by previous runs so RELEASE_001 validates a pristine
# distribution. Reports for this run are regenerated by qa_write_reports() below.
qa_reports_dir <- file.path(script_dir, "reports")
if (dir.exists(qa_reports_dir)) {
  stale_reports <- setdiff(
    list.files(qa_reports_dir, full.names = TRUE, all.files = TRUE, no.. = TRUE),
    file.path(qa_reports_dir, ".gitkeep")
  )
  if (length(stale_reports)) unlink(stale_reports, recursive = TRUE, force = TRUE)
}

source(file.path(QA_ROOT, "AAApp", "Common", "Engine", "Triple_A.R"), local = globalenv())
triple_a_load(QA_ROOT, install_missing = FALSE, envir = globalenv(), verbose = FALSE)
options(
  triplea.testing = TRUE,
  triplea.testing.root = file.path(tempdir(), "Triple_A_QualityAssurance")
)
dir.create(getOption("triplea.testing.root"), recursive = TRUE, showWarnings = FALSE)
qa_discover_tests(file.path(script_dir, "tests"))
level <- tolower(Sys.getenv("TRIPLE_A_TEST_LEVEL", "release"))
levels <- switch(
  level,
  smoke = "smoke",
  functional = c("smoke", "functional"),
  regression = c("smoke", "functional", "regression"),
  release = c("smoke", "functional", "regression", "release"),
  c("smoke", "functional", "regression", "release")
)
results <- qa_run_registered(levels)
qa_write_reports(QA_ROOT, results)
cat("\nReport: ", file.path(QA_ROOT, "QualityAssurance", "reports", "validation_report.txt"), "\n", sep = "")
if (any(results$status == "FAIL")) {
  stop("Quality assurance completed with failures. Review the report.", call. = FALSE)
}
invisible(results)
